name: expenses_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  sqflite: ^2.4.1
  sign_in_with_apple: ^7.0.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.0.0
  image_picker: ^1.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  provider: ^6.1.5+1
  emoji_picker_flutter: ^4.3.0
  flutter_sound: ^9.28.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_colorpicker: ^1.1.0
  build_runner: ^2.4.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoicon.png"
  ios_icon_settings:
    remove_alpha_ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
